name: test-lint-release
on:
  push:
    branches:
      - main
      - release
  pull_request:

env:
  NODE_VERSION: 18
  RELEASE_COMMAND: ${{ github.event.inputs.prerelease == 'true' &&  'release:prerelease' || 'release' }} -- ${{ github.event.inputs.release-it-options }}

jobs:
  lint:
    name: ⬣ Lint
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Install dependencies
        run: npm install

      - name: ▶️ Run lint script
        run: npm run lint

  test:
    name:
      🧪 Test (Node@${{ matrix.node }} - ESLint@${{ matrix.eslint }} - ${{
      matrix.os }})
    needs: [lint]
    strategy:
      matrix:
        eslint: [8]
        node: [16.0.0, 16, 18]
        os: [ubuntu-latest]
        include:
          # On other platforms
          - os: windows-latest
            eslint: 8
            node: 18
          - os: macos-latest
            eslint: 8
            node: 18
    runs-on: ${{ matrix.os }}
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup Node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ matrix.node }}

      - name: 📥 Install dependencies
        run: npm ci

      - name: 📥 Install ESLint v${{ matrix.eslint }}
        run: npm install eslint@${{ matrix.eslint }}

      - name: ▶️ Run test script
        run: npm run test -- --runInBand

      - name: ⬆️ Upload coverage report
        uses: codecov/codecov-action@v3

